#! /bin/bash
# Copyright (c) 2020 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source $NG_CORE/config/dp_config.cfg
SIMU_CP_FILE=$NG_CORE/config/simu_cp.cfg

echo -e "Generating $SIMU_CP_FILE..."
echo -e "# DO NOT EDIT!!! Autogenerated by simu_gen.sh...\n" > $SIMU_CP_FILE
echo "[0]" >> $SIMU_CP_FILE
echo "BASE_IMSI=$BASE_IMSI" >> $SIMU_CP_FILE
echo "BASE_MEI=$BASE_MEI" >> $SIMU_CP_FILE
echo "BASE_MSISDN=$BASE_MSISDN" >> $SIMU_CP_FILE
echo "APN_IDX=$APN_IDX" >> $SIMU_CP_FILE
echo "EPS_BEARER_ID=$EPS_BEARER_ID" >> $SIMU_CP_FILE
echo "BASE_S11_TEID=$BASE_S11_TEID" >> $SIMU_CP_FILE
echo "BASE_S1U_TEID=$BASE_S1U_TEID" >> $SIMU_CP_FILE
echo "ENB_START_IP=$ENB_START_IP" >> $SIMU_CP_FILE
echo "NUM_ENB=$NUM_ENB" >> $SIMU_CP_FILE
echo "S1U_SGW_IP=$S1U_IP" >> $SIMU_CP_FILE
echo "UE_START_IP=$UE_START_IP" >> $SIMU_CP_FILE
echo "UE_IP_RANGE=$UE_IP_RANGE" >> $SIMU_CP_FILE
echo "MAX_UE_SESS=$MAX_UE_SESS" >> $SIMU_CP_FILE
echo "DEFAULT_BEARER=5" >> $SIMU_CP_FILE
echo "TPS=$TPS" >> $SIMU_CP_FILE
echo "AS_START_IP=$AS_START_IP" >> $SIMU_CP_FILE
echo "BREAK_DURATION=60" >> $SIMU_CP_FILE


